### ISSUE TITLE
I cannot import the "Max" file into Blender.

### ISSUE THREAD

**Issue by elunesarrow54** [nrgsille76/io_scene_max#4]
For some reason, I couldn't import it. I'm sharing the error file.

Python: Traceback (most recent call last):
  File "C:\Users\egeme\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\__init__.py", line 92, in execute
    return import_max.load(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\egeme\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1544, in load
    read(context, os.path.join(directory, fl.name), mscale, obtypes=object_filter, search=use_image_search, transform=use_apply_matrix)
  File "C:\Users\egeme\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1516, in read
    read_class_directory(maxfile, filename)
  File "C:\Users\egeme\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 870, in read_class_directory
    clsdir.dll = get_dll(clsdir)
                 ^^^^^^^^^^^^^^^
  File "C:\Users\egeme\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 794, in get_dll
    idx = chunk.get_first(0x2060).data[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by nrgsille76** [comment]
Thanks for the report, this should now be fixed with commit  [ad139a3](https://github.com/nrgsille76/io_scene_max/commit/ad139a355e60fd652d7d987866f66f5ba1c1ffe0)
