### ISSUE TITLE
Will not import files from MAX 3.1

### ISSUE THREAD

**Issue by NCGraphics** [nrgsille76/io_scene_max#9]
Don't find any mention of which version of Max is supported. I still have a legal working version of MAX 3.1. If I try and import a file from this version, I get this error:

reading 'ClassData'... 270
reading 'Config'... 4109
reading 'DllDirectory'... 542
reading 'ClassDirectory3'... 52
reading 'VideoPostQueue'... 52
reading 'Scene'... 2523820
Traceback (most recent call last):
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max_init_.py", line 92, in execute
return import_max.load(self, context, **keywords)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1733, in load
read(context, os.path.join(directory, fl.name), mscale, obtypes=object_filter, search=use_image_search, transform=use_apply_matrix)
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1707, in read
read_scene(context, maxfile, settings, mscale, transform)
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1693, in read_scene
make_scene(context, settings, mscale, transform, SCENE_LIST[0])
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 1659, in make_scene
if isinstance(chunk, SceneChunk) and get_guid(chunk) == 0x1 and get_super_id(chunk) == 0x1:
^^^^^^^^^^^^^^^
File "C:\Users\tom\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\io_scene_max\import_max.py", line 879, in get_guid
return clid.get_first(0x2060).data[1]
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by nrgsille76** [comment]
@NCGraphics  Thanks for the report. This should be solved with commit 795c22f660af17cb3953007350073fae7b4fe6df

If the file does not import correctly, please upload it here, so I can reproduce the error.
